---
Name: custom-logging
Except:
  environment: dev
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      FileLogger: [ pushHandler, [ %$FileLogger ] ]
      MailHandler: [ pushHandler, [ %$MailHandler ] ]
  FileLogger:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "log/ss-errors.log"
      - "notice"
  MailHandler:
      class: Monolog\Handler\NativeMailerHandler
      constructor:
        - info@lucacattide.dev
        - There was an error on your site
        - info@lucacattide.dev
        - error
      properties:
        ContentType: text/html
        Formatter: %$SilverStripe\Logging\DetailedErrorFormatter
